name: test

on:
  push:
    branches:
    - master

jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p www/_site
        cat > www/_site/index.html <<EOL
        <!doctype html>
        <html>
          <head>
            <title>GH Pages deploy</title>
          </head>
          <body>
            <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/gh-pages-deploy">GH Pages deploy</a>.</p>
          </body>
        </html>
        EOL

    - name: Deploy
      if: success()
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
        EMAIL: arnaud@ligny.org
        BUILD_DIR: www/_site/
